### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by EternalHabit** [emoose/xenia#2]
1. Add VK_XBUTTON1 & VK_XBUTTON2 to bindings.ini using GetAsyncKeyState (I don't think IS_KEY_DOWN works for those buttons). Also VK_MENU (Alt) would be cool.

2. The mouse sensitivity in the main menu is slower than in the game. Maybe add an option inside xenia.config.toml to increase it? or make sensitivity in the menu higher. I use 0.395800 sensitivity and 800 DPI.

**Comment by emoose** [comment]
Just released v1.12 which should hopefully address these, XBUTTONs can be bound as mouse4/mouse5, while menu sensitivity is now a seperate ge_menu_sensitivity config var, let me know if you have any issues with them!
