### ISSUE TITLE
xenia.exe Does not get created when building the stfs-writer branch

### ISSUE THREAD

**Issue by Permdog99** [emoose/xenia#25]
[//]: # (Describe what's going wrong:)
I was trying to find a release of the "stfs-writer" branch and could not find one. So I decided build it myself. But when I do "xb build" after doing "xb setup" it looks like everything is fine until there are a load of errors and it says "ERROR: build failed with one or more errors." at the end.

[//]: # (Describe what should happen:)
I tried the master and that worked fine and even used Visual Studios to make it. Visual Studios says at the end that there is no xenia.exe. I looked at the build for both Release and Debug and there is no xenia.exe.

[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here)
[buildlog.txt](https://github.com/emoose/xenia/files/6580074/buildlog.txt)

**Comment by emoose** [comment]
Hmm, maybe try editing the "src/xenia/vfs/devices/stfs_xbox.h" file, and under the other #include lines add
`#include <xenia/xbox.h>`, then try a clean rebuild (`Rebuild all` in visual studio).

It's possible I broke something in one of my last rebase-fixups to that branch, I'll checkout that branch again later and see if I can fix it up, in case the above doesn't help.

**Comment by Permdog99** [comment]
> Hmm, maybe try editing the "src/xenia/vfs/devices/stfs_xbox.h" file, and under the other #include lines add
> `#include <xenia/xbox.h>`, then try a clean rebuild (`Rebuild all` in visual studio).
> 
> It's possible I broke something in one of my last rebase-merges to that branch, I'll checkout that branch again later and see if I can fix it up, in case the above doesn't help.

Thanks for the help. Adding that piece of text fixed the issue.
