### ISSUE TITLE
Saves not working properly in stfs-writer branch

### ISSUE THREAD

**Issue by Permdog99** [emoose/xenia#26]
[//]: # (Describe what's going wrong:)
So when I create a save in Minecraft for example, it loads up and everything is fine until I save & quit. When it is at the final stage of saving it freezes. I looked at the log and it is spitting out a LOAD of errors. Then it un-freezes and is back at the title screen. But when I join back into the world the game crashes and says the world is corrupted. I looked at the save files and the seem to be all the same amount of bytes. 4,127,028 KB to be exact. They were not the same amount before so it is kinda strange. I have tested this in only the stfs-writer branch and not the others because the saves do not even show up in them.

[//]: # (Describe what should happen:)

[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here)

**Comment by emoose** [comment]
Late here now but I'll try checking it with minecraft tomorrow, if you can upload the log file somewhere it might be useful.

The size difference is to be expected, stfs-writer wraps the saves in an STFS container now like the X360 itself uses, which rounds up the size to the nearest 4096 bytes or so (might be interesting to compare the size with one from an X360, or maybe see if an X360 save can be loaded)

**Comment by emoose** [comment]
Might have fixed this in the latest commit, tested with Minecraft TU0, previously the game would delete the save before writing a new one, but my code didn't actually clear all the deleted STFS blocks etc properly, with that fixed it looks like MC can save/load fine now, let me know how it goes for you.

**Comment by Permdog99** [comment]
> Might have fixed this in the latest 2 commits, tested with Minecraft TU0, previously the game would delete the save before writing a new one, but my code didn't actually clear all the deleted STFS blocks etc properly, so when it tried writing the new save there weren't any blocks available to write to.
> 
> With that fixed it looks like MC can save/load fine now, let me know how it goes for you.

Thanks. It works now.
